---
title: "Snowshoe Hare Analysis"
author: "Drew Andersen"
date: "11/7/2021"
output: html_document
---

```{r setup, include = TRUE, message = FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)

#attach packages
library(tidyverse)
library(janitor)
library(here)
library(lubridate)
library(kableExtra)
```
# 1. Overview

# 2. Data and methods
```{r}
#Read in and clean data
snowshoe <- read_csv(here("data","bonanza_hares.csv"))
```

# 3. Preliminary results

## A. Juvenile hare initial investigation:
```{r}
#subset for data visualization 
snowshoe_count <- snowshoe %>% 
  mutate(date_new = mdy(date)) %>% 
  mutate(year = year(date_new)) %>% 
  group_by(year) %>% 
  summarize(trap_count = n())

#in text referencing
trap_max <- max(snowshoe_count$trap_count)
trap_min <- min(snowshoe_count$trap_count)
trap_mean <- round(mean(snowshoe_count$trap_count),0)
trap_median <- median(snowshoe_count$trap_count)

#data_visualization
ggplot(data = snowshoe_count, aes(x = year, y = trap_count)) +
  geom_col(fill = "purple") +
  labs(title = "Juvenile Hare Trap Count",
       y = "Total Hares Trapped",
       x = NULL,
       caption = "Fig 1. Annual juvenile hare trap count between 1998-2012. This total reflects the number of juvenile hares trapped each year during this study.") +
  scale_x_continuous(breaks = 1998:2012) +
  theme_linedraw() 
```

## B. Juvenile Hare Weights 
```{r}
#subset for data visualization 
snowshoe_weight <- snowshoe %>% 
  mutate(site= case_when(
    grid == "bonrip" ~ "Bonanza Riparian",
    grid == "bonmat" ~ "Bonanza Mature",
    grid == "bonbs" ~ "Bonds")) %>% 
  mutate(sex = case_when(
    sex == "m" ~ "Male",
    sex == "f" ~ "Female",
    is.na(sex) ~ "Unconfirmed"))

#histogram of weight distributions by sex and site
ggplot(data = snowshoe_weight, aes(weight)) +
  geom_histogram(bins = 25, aes(fill = sex)) +
  facet_wrap(~site) +
  scale_fill_manual(values = c("hotpink","skyblue2","snow4")) +
  labs(title = "Juvenile Hare Weight by Trap Site",
       y = "Count",
       x = "Weight (g)",
       caption = "Fig 2. Juvenile hare weight distribution by site and sex. The group marked NA")
```

## C. Juvenile Hare Weight Comparison
```{r}
snowshoe_stats <- snowshoe_weight %>% 
  filter(sex != "Unconfirmed") %>% 
  group_by(sex) %>% 
  summarize(sample_size = n(),
            mean = round(mean(weight, na.rm = TRUE),0),
            std_dev = round(sd(weight, na.rm = TRUE),0))

snowshoe_stats %>% 
  kable(col.names = c("Sex", #renaming the column names from their variable names
                      "Sample Size", 
                      "Mean Weight (g)",
                      "Standard Deviation (g)"),
        caption = "Table 1. Summary statistics for male and female juvenile hare weights.") %>% 
  kable_styling(full_width = FALSE)
```

## D. Weight and Hind Foot Length 
#### Summary
#### Citations

